# Generated by Django 5.0.2 on 2024-12-04 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_reservation_reservation_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='country_code',
        ),
    ]
