# Generated by Django 5.0.2 on 2024-11-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='host_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
